"""REPORT.md generation for a discovery run."""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from .pipeline import DiscoveryResult


def _confidence(cand_flags: Dict[str, Any], n_bridges: int, score: float) -> str:
    """Coarse, deliberately conservative confidence label for a survivor."""
    ac = cand_flags.get("ac_cooccurrence", 0) or 0
    pre = cand_flags.get("preprint_hits", 0) or 0
    if n_bridges >= 6 and ac == 0 and pre == 0 and score >= 8:
        return "moderate"
    if n_bridges >= 3 and ac == 0:
        return "low-moderate"
    return "low"


def write_report(
    runs: List[DiscoveryResult],
    survivors_by_a: Dict[str, List[Any]],
    cfg: Dict[str, Any],
    path: str,
    validation_summary: str,
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    L: List[str] = []
    L.append("# REPORT.md - Literature-Based Discovery run\n")
    L.append(f"_Generated {now}._\n")

    L.append("## Validation gate\n")
    L.append(validation_summary + "\n")

    L.append("## A-terms searched\n")
    L.append("| A-term (input) | MeSH descriptor | A-corpus size | B-terms expanded | C-candidates | Survivors |")
    L.append("|---|---|---|---|---|---|")
    for r in runs:
        nsurv = len(survivors_by_a.get(r.a_name, []))
        L.append(f"| {r.a_input} | {r.a_name} | {r.corpus_size} | {r.n_b_terms} | {r.n_candidates} | {nsurv} |")
    L.append("")

    L.append("## Survivors (cleared the full novelty / false-positive cascade)\n")
    any_surv = False
    for r in runs:
        survs = survivors_by_a.get(r.a_name, [])
        if not survs_nonempty(survs):
            continue
        any_surv = True
        L.append(f"### A = {r.a_name}\n")
        L.append("| Rank | C (proposed link) | Bridges | Score | A-C co-occ | Preprint hits | Confidence |")
        L.append("|---|---|---|---|---|---|---|")
        for i, (cand, outcome) in enumerate(survs, start=1):
            conf = _confidence(cand.flags, cand.n_bridges, cand.score)
            L.append(f"| {i} | {cand.c_term} | {cand.n_bridges} | {cand.score:.2f} | "
                     f"{cand.flags.get('ac_cooccurrence','?')} | {cand.flags.get('preprint_hits','?')} | {conf} |")
        L.append("")
    if not any_surv:
        L.append("_No candidates cleared the full cascade in this run._\n")

    L.append("## Honest confidence and caveats\n")
    L.append("- These are **hypotheses generated by literature structure, not findings**. Each is a "
             "candidate A--C link that is currently unstudied in the indexed literature and is bridged "
             "by shared intermediates. None has been experimentally tested here.")
    L.append("- Substrate is MeSH-term co-occurrence over PubMed (see DATA.md). Co-occurrence is "
             "undirected, so the *sign* of each mechanistic edge (e.g. raises vs. lowers) is not "
             "verified; the mechanistic-coherence gate is reported as a warning, not a pass, for every "
             "candidate. A domain expert must check that the chain is directionally sensible.")
    L.append("- The 'gap' is a gap **in the indexed literature**: absence of co-occurrence/preprint "
             "evidence, not proof no one has ever considered the link.")
    L.append("- Ranking favors candidates with many independent bridges and strong edges; this biases "
             "toward well-studied intermediates and can surface generic physiology. Read the brief, not "
             "just the rank.")
    L.append("")
    L.append("> Every hypothesis here requires expert appraisal and experimental validation before it "
             "should be treated as anything more than a lead.\n")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))


def survs_nonempty(survs) -> bool:
    return survs is not None and len(survs) > 0
